name: companies
version: '1.0-SNAPSHOT'
main: me.wiceh.companies.Companies
api-version: '1.20'
authors: [ wIceh ]
commands:
  company:
    aliases:
      - azienda
  cashregister:
    aliases:
      - cassa
      - cash-register
  annuncio:
  admincompany:
    aliases:
      - adminazienda
  bcsign:
    description: Imposta un cartello per l'annuncio di un'azienda
  bcaccept:
    description: Accetta una richiesta di annuncio